### ISSUE TITLE
[Bug]: Site can’t be reached

### ISSUE THREAD

**Issue by Theelasthokage** [Derpitron/Discord-OTP-Forcer#112]
### Description

When I type scripts/Windows/start.bat Chrome will open but I get This site can’t be reached error and I click the reload and nothing happens. I get stuck at this part

### Minimal Reproduction

I typed “scripts/Windows/start.bat” in the command bar where the repository sits and get an error in Chrome

### Error

Please see attached 
![image](https://github.com/Derpitron/Discord-OTP-Forcer/assets/166664936/aad3aed9-8555-404f-b5da-eb8300053047)

### Operating System Version

Unknown

### Python Version

3.12

### Program Version 

I’m not sure 

### Any other information or context?

I’m locked out of my discord and just trying to bypass the 2FA

**Comment by Derpitron** [comment]
You have to run the command `./scripts/Windows/start.bat` in your command prompt/powershell, not the web browser

**Comment by Theelasthokage** [comment]
I fixed it thank you, I noticed no one shares how long it takes for this?

**Comment by Derpitron** [comment]
It's unknown for sure how much time it could take. Success is not guaranteed. Good luck

**Comment by Theelasthokage** [comment]
Thank you so much for this! I’m sorry for the crazy questions, but does the hcaptcha have a time limit? Let’s say if it pops up in the middle of the night and I don’t see it until morning will it still work?

**Comment by Derpitron** [comment]
I have no clue honestly, never tried it.

Also do please put your other questions in the Discussions section. Best not to clutter this : )
