### ISSUE TITLE
[Bug]: script is ineffective after 10 min of working in login/normal modes

### ISSUE THREAD

**Issue by jurbek** [Derpitron/Discord-OTP-Forcer#117]
### Description

I tested the script on the account I've got Authenticator app for. I filled in the correct code after 5/10/15 min from the start of script execution and found out that if the script is running for more than 10 min, it will always say 'Invalid two-factor code' even if you filled in the correct code from your Authenticator app.

As mentioned here (https://github.com/Derpitron/Discord-OTP-Forcer/issues/58), the program is supposed to re-run once it hits 300 sec mark but that doesn't happen in login/normal mode anymore.

Question: what would happen if the TOTP code actually worked while I'm afk. Will the script still be running and reset the successful log-in after 300 sec?

Thanks!

### Minimal Reproduction

1. Run the script for >10 min in login/normal mode
2. Put the correct TOTP code

### Error

"Invalid two-factor code"

### Operating System Version

Win10

### Python Version

Python 3.10

### Program Version 

latest

**Comment by Derpitron** [comment]
I'm not able to reproduce this at all. I've been running for over 10 minutes, and there is no error at all.

Do you do anything else while the program is running? E.g lock your PC?

**Comment by jurbek** [comment]
The error is "Invalid two-factor code" while the TOTP code is actually valid and correct (because it's from Authenticator app)

![image](https://github.com/Derpitron/Discord-OTP-Forcer/assets/165653271/7cbc2685-d92e-491f-a784-ce03274cdbe4)

**Comment by Derpitron** [comment]
Invalid two-factor code, while the code in the screenshot was actually correct?

**Comment by jurbek** [comment]
Yeah!

**Comment by Derpitron** [comment]
As I'm not able to reproduce this bug myself I can't test or implement this.

It might be better if you created a cronjob to run/kill the program every 10 minutes.
