### ISSUE TITLE
I keep on getting command not found.. what is the problem?

### ISSUE THREAD

**Issue by Lindaath** [Derpitron/Discord-OTP-Forcer#12]
SetFile                        mnthome
SophosUpdate                   moo-outdated
MacBook-Pro:Discord-OTP-Forcer ath$ ame__ == "__main__":
-bash: ame__: command not found
MacBook-Pro:Discord-OTP-Forcer $ # Run the program.
MacBook-Pro:Discord-OTP-Forcer $ main()

**Comment by Lindaath** [comment]
MacBook-Pro:~ $ python-dotenv
-bash: python-dotenv: command not found
MacBook-Pro:~ $ selenium==4.1.5
MacBook-Pro:~ $ webdriver_manager

this also happens when I try to plug in the requirements

**Comment by Derpitron** [comment]
This program needs to be run using the Python Interpreter. 

Install Python on your system, go to the folder where you've installed/downloaded this program, and run the following command:
```
python src/main.py
```

If this still does not work for you, let me know and I'll help you.

**Comment by Derpitron** [comment]
Closing as solved due to no further activity.
