### ISSUE TITLE
[Bug]: AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by benchahfd74** [Derpitron/Discord-OTP-Forcer#124]
### Description

I've got this error {AttributeError: 'NoneType' object has no attribute 'get'} when I tried to run the [start.bat]

### Minimal Reproduction

Python 3.12
Windows 11 pro

### Error

[2024-07-01 15:51:41] [DEBUG] - __main__:load_configuration:33 - Loaded configuration file located at ******
File "C:\Users\AHMED_\Desktop\Discord-OTP-Forcer-main\main.py", line 87, in <module>
    83
    84   if __name__ == '__main__':
    85          try:
    86                  logger.remove()
--> 87                  userFacing(load_configuration())
    88          except UserCausedHalt:
    ..................................................
     __name__ = '__main__'
     logger.remove = <method 'Logger.remove' of <loguru.logger handlers=[(id=1, l
                      evel=10, sink=<stderr>)]> _logger.py:1013>
    ..................................................

File "C:\Users\AHMED_\Desktop\Discord-OTP-Forcer-main\main.py", line 81, in userFacing
    36   def userFacing(configuration: dict):
 (...)
    77          if configuration['codeMode'].lower() not in validCodeModes: raise ValueError('Invalid code-generation mode inputted!')
    78
    79          # Start the simulated browser, and run it in an infinite loop.
    80          while True:
--> 81                  driver = bootstrap_browser(configuration)
    82                  bootstrap_login_page(driver, configuration)
    ..................................................
     configuration = {'email': '',
                      'password': '',
                      'programMode': 'reset',
                      'codeMode': 'backup',
                   
                      'authToken': '',
                      'sensitiveDebug': 'True',
                      'logCreation': 'False'}
     validCodeModes = {'both', 'backup', 'backup_let', 'normal', }
    ..................................................

File "C:\Users\AHMED_\Desktop\Discord-OTP-Forcer-main\src\backend.py", line 48, in bootstrap_browser
    27   def bootstrap_browser(
    28          configuration: dict,
    29   ) -> webdriver.chrome.webdriver.WebDriver:
 (...)
    44          #options.add_argument('--headless')
    45          #options.add_argument('--log-level=1')
    46
    47          # Get and initialize the most up-to-date Chromium web driver
--> 48          driver = webdriver.Chrome(service=ChromiumService(ChromeDriverManager(chrome_type=ChromeType.CHROMIUM).install()), options=options)
    49          logger.debug('Starting Chromium browser')
    ..................................................
     configuration = {'email': '',
                      'password': '',
                      'programMode': 'reset',
                      'codeMode': 'backup',
                     
                      'authToken': '',
                      'sensitiveDebug': 'True',
                      'logCreation': 'False'}
     ChromeType.CHROMIUM = 'chromium'
     options = <selenium.webdriver.chrome.options.Options object at 0x00000
                2DE8DD8FDA0>
     logger.debug = <method 'Logger.debug' of <loguru.logger handlers=[(id=1, le
                     vel=10, sink=<stderr>)]> _logger.py:2038>
    ..................................................

File "C:\Users\AHMED_\AppData\Local\Programs\Python\Python312\Lib\site-packages\webdriver_manager\chrome.py", line 40, in install
    39   def install(self) -> str:
--> 40       driver_path = self._get_driver_binary_path(self.driver)
    41       os.chmod(driver_path, 0o755)
    ..................................................
     self = <webdriver_manager.chrome.ChromeDriverManager object at 0x00
             0002DE8FD755B0>
     self._get_driver_binary_path = <method 'DriverManager._get_driver_binary_path' of <webdrive
                                     r_manager.chrome.ChromeDriverManager object at 0x000002DE8FD
                                     755B0> manager.py:34>
     self.driver = <webdriver_manager.drivers.chrome.ChromeDriver object at 0x0
                    00002DE9021A2D0>
    ..................................................

File "C:\Users\AHMED_\AppData\Local\Programs\Python\Python312\Lib\site-packages\webdriver_manager\core\manager.py", line 40, in _get_driver_binary_path
    34   def _get_driver_binary_path(self, driver):
 (...)
    36       if binary_path:
    37           return binary_path
    38
    39       os_type = self.get_os_type()
--> 40       file = self._download_manager.download_file(driver.get_driver_download_url(os_type))
    41       binary_path = self._cache_manager.save_file_to_cache(driver, file)
    ..................................................
     self = <webdriver_manager.chrome.ChromeDriverManager object at 0x00
             0002DE8FD755B0>
     driver = <webdriver_manager.drivers.chrome.ChromeDriver object at 0x0
               00002DE9021A2D0>
     binary_path = None
     os_type = 'win32'
     self.get_os_type = <method 'ChromeDriverManager.get_os_type' of <webdriver_mana
                         ger.chrome.ChromeDriverManager object at 0x000002DE8FD755B0>
                          chrome.py:44>
     self._download_manager.download_file = <method 'WDMDownloadManager.download_file' of <webdriver_man
                                             ager.core.download_manager.WDMDownloadManager object at 0x00
                                             0002DE8DFC0770> download_manager.py:27>
     driver.get_driver_download_url = <method 'ChromeDriver.get_driver_download_url' of <webdriver
                                       _manager.drivers.chrome.ChromeDriver object at 0x000002DE902
                                       1A2D0> chrome.py:31>
     self._cache_manager.save_file_to_cache = <method 'DriverCacheManager.save_file_to_cache' of <webdrive
                                               r_manager.core.driver_cache.DriverCacheManager object at 0x0
                                               00002DE8DEC8980> driver_cache.py:51>
    ..................................................

File "C:\Users\AHMED_\AppData\Local\Programs\Python\Python312\Lib\site-packages\webdriver_manager\drivers\chrome.py", line 32, in get_driver_download_url
    31   def get_driver_download_url(self, os_type):
--> 32       driver_version_to_download = self.get_driver_version_to_download()
    33       # For Mac ARM CPUs after version 106.0.5249.61 the format of OS type changed
    ..................................................
     self = <webdriver_manager.drivers.chrome.ChromeDriver object at 0x0
             00002DE9021A2D0>
     os_type = 'win32'
     self.get_driver_version_to_download = <method 'Driver.get_driver_version_to_download' of <webdrive
                                            r_manager.drivers.chrome.ChromeDriver object at 0x000002DE90
                                            21A2D0> driver.py:39>
    ..................................................

File "C:\Users\AHMED_\AppData\Local\Programs\Python\Python312\Lib\site-packages\webdriver_manager\core\driver.py", line 48, in get_driver_version_to_download
    39   def get_driver_version_to_download(self):
 (...)
    44       """
    45       if self._driver_version_to_download:
    46           return self._driver_version_to_download
    47
--> 48       return self.get_latest_release_version()
    ..................................................
     self = <webdriver_manager.drivers.chrome.ChromeDriver object at 0x0
             00002DE9021A2D0>
     self._driver_version_to_download = None
     self.get_latest_release_version = <method 'ChromeDriver.get_latest_release_version' of <webdri
                                        ver_manager.drivers.chrome.ChromeDriver object at 0x000002DE
                                        9021A2D0> chrome.py:54>
    ..................................................

File "C:\Users\AHMED_\AppData\Local\Programs\Python\Python312\Lib\site-packages\webdriver_manager\drivers\chrome.py", line 64, in get_latest_release_version
    54   def get_latest_release_version(self):
 (...)
    60           response_dict = json.loads(response.text)
    61           determined_browser_version = response_dict.get("builds").get(determined_browser_version).get("version")
    62           return determined_browser_version
    63       # Remove the build version (the last segment) from determined_browser_version for version < 113
--> 64       determined_browser_version = ".".join(determined_browser_version.split(".")[:3])
    65       latest_release_url = (
    ..................................................
     self = <webdriver_manager.drivers.chrome.ChromeDriver object at 0x0
             00002DE9021A2D0>
     json.loads = <function 'loads' __init__.py:299>
     determined_browser_version = None
     determined_browser_version.split = # AttributeError
          determined_browser_version = None
    ..................................................

---- (full traceback above) ----
File "C:\Users\AHMED_\Desktop\Discord-OTP-Forcer-main\main.py", line 87, in <module>
    userFacing(load_configuration())
File "C:\Users\AHMED_\Desktop\Discord-OTP-Forcer-main\main.py", line 81, in userFacing
    driver = bootstrap_browser(configuration)
File "C:\Users\AHMED_\Desktop\Discord-OTP-Forcer-main\src\backend.py", line 48, in bootstrap_browser
    driver = webdriver.Chrome(service=ChromiumService(ChromeDriverManager(chrome_type=ChromeType.CHROMIUM).install()), options=options)
File "C:\Users\AHMED_\AppData\Local\Programs\Python\Python312\Lib\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
File "C:\Users\AHMED_\AppData\Local\Programs\Python\Python312\Lib\site-packages\webdriver_manager\core\manager.py", line 40, in _get_driver_binary_path
    file = self._download_manager.download_file(driver.get_driver_download_url(os_type))
File "C:\Users\AHMED_\AppData\Local\Programs\Python\Python312\Lib\site-packages\webdriver_manager\drivers\chrome.py", line 32, in get_driver_download_url
    driver_version_to_download = self.get_driver_version_to_download()
File "C:\Users\AHMED_\AppData\Local\Programs\Python\Python312\Lib\site-packages\webdriver_manager\core\driver.py", line 48, in get_driver_version_to_download
    return self.get_latest_release_version()
File "C:\Users\AHMED_\AppData\Local\Programs\Python\Python312\Lib\site-packages\webdriver_manager\drivers\chrome.py", line 64, in get_latest_release_version
    determined_browser_version = ".".join(determined_browser_version.split(".")[:3])

AttributeError: 'NoneType' object has no attribute 'split'

### Operating System Version

Windows 11 pro

### Python Version

Python 3.12

### Program Version 

master branch

### Any other information or context?

I don't have any other info but why is the program only compatible with chrome version 122?
I will appriciate if you responde quickly.

**Comment by Derpitron** [comment]
Hi, please install the google-chrome branch version. The main branch uses Chromium which is different.

**Comment by CerberusGuard** [comment]
> Hi, please install the google-chrome branch version. The main branch uses Chromium which is different.

Which version of chrome? There are 4 Stable, Dev, Beta, Canary?

**Comment by Derpitron** [comment]
Stable
