### ISSUE TITLE
[Bug]: 2FA Auth starts getting rate limited after 30 minutes of Attempts

### ISSUE THREAD

**Issue by CheddarBin** [Derpitron/Discord-OTP-Forcer#125]
### Description

Rate limiting bypass works as normal up until around the 30 minute mark when I start getting a "Service Resource is being rate limited" Error every other attempt

### Minimal Reproduction

Ran program in 2FA, Waited. Starting seeing error about 30 minutes into brute force.

### Error

![image_2024-07-07_040241258](https://github.com/Derpitron/Discord-OTP-Forcer/assets/174930081/90d3d992-5eaa-46c0-88d5-0aa4293e8981)

### Operating System Version

Win 10

### Python Version

Latest

### Program Version 

dc02254

**Comment by Derpitron** [comment]
I was recieving this same error.

Try downloading the latest version of google-chrome-compat, and let me know if it still has a problem.

**Comment by CheddarBin** [comment]
Rate Limiting is now being detected properly. Cheers mate!

**Comment by nyathea** [comment]
im getting this issue now.
