### ISSUE TITLE
[Bug]: ElementNotInteractableException: Website hangs when submitting a code, crashing the program.

### ISSUE THREAD

**Issue by mglass99** [Derpitron/Discord-OTP-Forcer#129]
### Description

Was running program on normal login mode. It has randomly stopped working after a few hours every time. See attachment for info provided after the last code attempt.

[bug report.txt](https://github.com/user-attachments/files/16400965/bug.report.txt)

### Minimal Reproduction

All I did was run program for a few hours. It happens without any additional input after program start.

### Error

[bug report.txt](https://github.com/user-attachments/files/16400970/bug.report.txt)

### Operating System Version

Windows 10 19045.4651

### Browser and Browser Version

126.0.6478.185 (Official Build) (64-bit)

### Python Version

3.10

### Program Version 

fc9812f3b6769f0eeba42f0f5bdeb01b7c8fe57c

**Comment by Derpitron** [comment]
I'm not experiencing this error. Please send the full stack trace with redacted personal details.

**Comment by mglass99** [comment]
> I'm not experiencing this error. Please send the full stack trace with redacted personal details.

Where do I find that? I'm not well versed in any of this coding stuff.

**Comment by Derpitron** [comment]
... The giant error that pops up in your console/terminal app when  the program crashes. Copy that and send it to me, please

**Comment by mglass99** [comment]
> ... The giant error that pops up in your console/terminal app when the program crashes. Copy that and send it to me, please

All the stuff in red? I already have that as part of the .txt file in the original post

**Comment by Derpitron** [comment]
This error happens to me too. I'm not sure what the cause is.
I guess that after hours of running, the website lags to an extent that the program just breaks.

When I have time I will have to watch the log and screen manually to find out what causes it.

**Comment by mglass99** [comment]
I just had a different error occur. Attached a file of everything in the cmd.exe after the last code attempt, with email & password redacted.

[timeout error.txt](https://github.com/user-attachments/files/16512147/timeout.error.txt)

**Comment by mglass99** [comment]
Here is a video of the error happening https://youtu.be/giHWegeAyrM

**Comment by Derpitron** [comment]
Seems to be the website takes too long to submit the code, due to the ratelimit.

I thought I fixed this before but apparently not. I'm not sure what the solution is.

**Comment by mglass99** [comment]
Is there a way to increase the time between codes instead of it starting at 2 seconds? Like, make it submit between 4-8 seconds?

**Comment by Derpitron** [comment]
You can edit the cooldown in the program. There should be some hardcoded values. search for time.sleep(

**Comment by mglass99** [comment]
In which folder/document?
