### ISSUE TITLE
Re-execute after timeout

### ISSUE THREAD

**Issue by Subtilizer28** [Derpitron/Discord-OTP-Forcer#13]
Is it possible to get the program automatically execute again after discord timeout? Would reduce time.

**Comment by Derpitron** [comment]
This program automatically resumes after discord ratelimits the token input.

But, if Discord/the program says "invalid ticket", then it means that the login session has expired, and it needs to be manually re-run by the user. This is something which cannot be automated by the program, hence must be done manually.

**Comment by Derpitron** [comment]
Closing as solved due to no further activity.
