### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by subwaysimon** [Derpitron/Discord-OTP-Forcer#130]
### Description

Every time I run it, it gives me this error I dont know what to do

### Minimal Reproduction

Did the setup, Filled in info, Clicked run

### Error

![Screenshot 2024-07-31 231723](https://github.com/user-attachments/assets/535c3384-5e99-4a78-a61f-8413712e9c34)

### Operating System Version

10

### Browser and Browser Version

Opera GX Latest

### Python Version

3.11

### Program Version 

Most Recent

**Comment by Derpitron** [comment]
Did you run
```pip install -r requirements.txt```?
