### ISSUE TITLE
[Bug]: chrome version issue

### ISSUE THREAD

**Issue by progressEdd** [Derpitron/Discord-OTP-Forcer#131]
### Description

I got the same error as reported in https://github.com/Derpitron/Discord-OTP-Forcer/discussions/128

There are 2 solutions:
1. replace webdriver-manager with chromedriver-autoinstaller [github](https://github.com/yeongbin-jo/python-chromedriver-autoinstaller), [pypy](https://pypi.org/project/chromedriver-autoinstaller/) 
    - The main advantage of this solution is the user doesn't need to install chrome/chromium
    - I will make a branch with the changes to the code [pr here](https://github.com/Derpitron/Discord-OTP-Forcer/pull/132)
2. install chromium and hope the path gets automatically recognized
    - When I installed it with the Fedora package manager, the path got automatically recognized. I haven't tested it on windows or other systems

### Minimal Reproduction

the issue appears to be with webdriver-manager, which is using a older chromium version.

### Error

```python
home/progressedd/miniconda3/envs/discord-otp/bin/python /home/bedh
edd/Documents/Discord-OTP-Forcer/src/upgradechromium.py
Traceback (most recent call last):
  File "/home/progressedd/Documents/Discord-OTP-Forcer/src/upgradechromium.py", line 6, in <module>
    driver = webdriver.Chrome(service=ChromiumService(ChromeDriverManager(chrome_type=ChromeType.CHROMIUM).install()))
  File "/home/progressedd/miniconda3/envs/discord-otp/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/progressedd/miniconda3/envs/discord-otp/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/progressedd/miniconda3/envs/discord-otp/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 212, in __init__
    self.start_session(capabilities)
  File "/home/progressedd/miniconda3/envs/discord-otp/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 299, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/home/progressedd/miniconda3/envs/discord-otp/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/home/progressedd/miniconda3/envs/discord-otp/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 127.0.6533.99 with binary path /usr/bin/google-chrome
Stacktrace:
#0 0x5630027cd4e3 <unknown>
#1 0x5630024fcc76 <unknown>
#2 0x56300252a04a <unknown>
#3 0x5630025254a1 <unknown>
#4 0x563002522029 <unknown>
#5 0x563002560ccc <unknown>
#6 0x56300256047f <unknown>
#7 0x563002557de3 <unknown>
#8 0x56300252d2dd <unknown>
#9 0x56300252e34e <unknown>
#10 0x56300278d3e4 <unknown>
#11 0x5630027913d7 <unknown>
#12 0x56300279bb20 <unknown>
#13 0x563002792023 <unknown>
#14 0x5630027601aa <unknown>
#15 0x5630027b66b8 <unknown>
#16 0x5630027b6847 <unknown>
#17 0x5630027c6243 <unknown>
#18 0x7f073dc1f897 start_thread
#19 0x7f073dca6a5c __clone3
```

### Operating System Version

Fedora 39

### Browser and Browser Version

127.0.6533.99

### Python Version

3.10

### Program Version 

latest

**Comment by Derpitron** [comment]
I'm removing the `chromedriver-autoinstaller patch` #132  and `webdriver_manager` from the program, because at least for me (Arch Linux, running `google-chrome` from AUR) I've often seen chromedriver-autoinstaller fail to get the correct version for a few weeks.

Instead i'll implement [undetected-chromedriver](https://github.com/ultrafunkamsterdam/undetected-chromedriver) which also auto-downloads the correct Chrome version (Chromium not yet implemented), and seems to be more reliable to me. This works on both Arch Linux and Windows from some limited testing
