### ISSUE TITLE
[Bug]: Nothing seems to happen when running

### ISSUE THREAD

**Issue by qWampy** [Derpitron/Discord-OTP-Forcer#133]
### Description

Sorry for the inconvenience but I cannot fix this tough I have no knowledge on how it works but after I downloaded all the requirements and set all the information up I just get this issue, sorry if this is just my stupidity

### Minimal Reproduction

I just dowloaded all the requirements and set up the information, but got this error.

### Error

![image](https://github.com/user-attachments/assets/4a646dd7-5a3f-4ff6-b9e5-9e5ef9c76b51)

### Operating System Version

windows11

### Browser and Browser Version

Chrome, Chrome 114

### Python Version

3.10

### Program Version 

Cant find what the latest version is called, but im using the latest.

**Comment by Derpitron** [comment]
Hi, is there any more info available below that line of error?

You may need to update your Google Chrome build and use the google-chrome-compat branch.

**Comment by qWampy** [comment]
No, there is no line bellow it. Also what do you mean by update the google chrome build? Thank you so much for the help.

**Comment by Derpitron** [comment]
Update your Google Chrome app

And nothing happens at all when you run the script? No other window opens?

**Comment by qWampy** [comment]
Yeah absulutely nothing else happens, it just stays in limbo forever. Just tried it with the updated version and still nothing.

**Comment by Derpitron** [comment]
Does this still happen for you now? Please recheck with the latest version

**Comment by qWampy** [comment]
Yes thank you the issue is fixed now. Thank you so much for the help.
