### ISSUE TITLE
Kind of an unrelated question:

### ISSUE THREAD

**Issue by Trxnce** [Derpitron/Discord-OTP-Forcer#14]
Is there any way to bypass the thing where it tells you that you have to reset your password to log in?

**Comment by Derpitron** [comment]
I am not sure about that. Can you please elaborate?

**Comment by Trxnce** [comment]
I can't execute it because it's telling me to reset my password to log in,
is there any known way àround that?

**Comment by Derpitron** [comment]
I have not encountered this issue before.

Try to reset your password then  retry.

If I may ask, how long has your account been locked out?

**Comment by Trxnce** [comment]
It's been locked out for over a year now, and you need 2FA to reset the
password as well

**Comment by Derpitron** [comment]
That is such a stupid system! I regrettably do not have the time to make a complex system for password reset AND 2FA as of now, but I think it would be easy to do, if you have skills with Python and Selenium.

https://www.youtube.com/watch?v=Xjv1sY630Uc&list=PLzMcBGfZo4-n40rB1XaJ0ak1bemvlqumQ I recommend you watch this free playlist by Tech With Tim, on learning Selenium. It may help you out if you want to tackle this problem yourself.

**Comment by LuXeZs** [comment]
> Is there any way to bypass the thing where it tells you that you have to reset your password to log in?

You still need help with this? I had the same problem and I've altered this a bit and got it to work for the password reset

**Comment by Derpitron** [comment]
If you publically release your edited version, please do submit a pull request to this repository. I can merge it in that way

**Comment by Trxnce** [comment]
Hi, yeah I do.

**Comment by Trxnce** [comment]
> 

That would be greatly appreciated to have, I'm surprised you were able to.

**Comment by Derpitron** [comment]
This feature is soon to be added in. Check in at #15 for the progress.

**Comment by Trxnce** [comment]
I also have a question. Did you guys use Google Auth or something else?

**Comment by Trxnce** [comment]
> > Did you guys use Google Auth or something else?
> 
> I personally use a KeePass database for my passwords and OTP codes. I used to store it on Dropbox so I could use it on both my phone and computer. But, the dropbox mobile client had file syncing issues on my phone around 1 year ago, which caused total data loss. I had to roll back to an earlier version of my password database which was missing the credentials for my Discord account, including both the TOTP and backup codes for it.
> 
> I contacted Discord support for help, and they told me that they could not reset my 2fa or backup codes, leaving the account effectively locked out.
> 
> I refused to accept this, so I made this program and have been trying (yet failing) to get back my account.

I figured as much, as even just brute forcing is a very lengthy process for passwords but especially when it comes to OTPs. I've been struggling with this as well.
