### ISSUE TITLE
How does one run this?

### ISSUE THREAD

**Issue by Dreskel** [Derpitron/Discord-OTP-Forcer#17]
I am absolutely new to this kind of stuff and i _really_ need this to work, if there is any possible way to get a proper tutorial to run this as someone who'd never touched such things in the past, this would be utterly a god send

**Comment by Dreskel** [comment]
It would be utterly amazing if this could be packaged into an easy to use executable for people with no coding understanding at all

**Comment by Derpitron** [comment]
See #9 for some help.

Unfortunately I don't have the time to make a proper tutorial right now, sorry.
