### ISSUE TITLE
Not correctly deleting old code when entering backup codes

### ISSUE THREAD

**Issue by Micromot20** [Derpitron/Discord-OTP-Forcer#19]
I'm trying to use it on the password reset form and it is not fully deleting the old code before trying to enter the next generated code,

**Comment by LuXeZs** [comment]
Ah I see what's wrong and have fixed it #20

**Comment by Derpitron** [comment]
@Micromot20 Let me and @LuXeZs know if this issue reoccurs for you.

Thank you, @LuXeZs for this patch!
