### ISSUE TITLE
How to use on password reset?

### ISSUE THREAD

**Issue by Micromot20** [Derpitron/Discord-OTP-Forcer#2]
Is there a program that is able to brute force the 2FA on the password reset form because I lost my 2FA codes and forgot my password?

If there isn't, how do I do that?

**Comment by hydino2085143** [comment]
If you've lost your password as well as your 2FA code, then I have no idea what you can do. this program is meant for if you have a username and password.

I don't know how exactly the password reset form works with 2FA codes, but it should be easy to adapt my program for your needs. Don't give up hope

**Comment by Micromot20** [comment]
I am not that good with coding, so I'll have to wait for someone else to publish such a Program. The Discord Support is really frustrating so any wait time is better than that. Thanks for the response though!

**Comment by Derpitron** [comment]
May be related: #15
