### ISSUE TITLE
reqiurements

### ISSUE THREAD

**Issue by throwaway12345678910111** [Derpitron/Discord-OTP-Forcer#21]
so i have the software and i tried running the main.py but it says I don't have the requirements (the ones from the txt file) and I have no clue how to install them. can you give an explanation on how to do this

**Comment by LuXeZs** [comment]
Run `pip install -r requirements.txt` it should then install the requirements.

I suggest you read the [how to use](https://github.com/Derpitron/Discord-OTP-Forcer#how-to-use) section it should help, if you have anymore questions I'll be happy to help.
