### ISSUE TITLE
`.env` and `.gitignore` files not found when downloading .zip of/cloning the repo

### ISSUE THREAD

**Issue by nightninja56** [Derpitron/Discord-OTP-Forcer#24]
Sorry, am new to this stuff but trying my best. I can't seem to find the .env file in the zipped folder that I downloaded. Everything else seems to be there and I have python/git downloaded, but I can't find that .env file.

**Comment by LuXeZs** [comment]
If you have git installed I would recommend opening command prompt and doing,

`git clone https://github.com/hydino2085143/Discord-OTP-Forcer.git` 

This should download the files into your main user directory from here I would read the instructions on the [Main Page](https://github.com/Derpitron/Discord-OTP-Forcer#how-to-use).
If you have anymore questions I'll be happy to help.

**Comment by nightninja56** [comment]
Yeah, so this is all I see in the directory when I clone like that: 
<img width="614" alt="Screen Shot 2023-04-14 at 9 14 53 PM" src="https://user-images.githubusercontent.com/130790643/232182350-986ecaa1-6316-4375-9acd-84609f03c6a6.png">

**Comment by LuXeZs** [comment]
You could create a .env file and paste the content from the [.env file](https://github.com/Derpitron/Discord-OTP-Forcer/blob/main/.env).

Are you on a mac? I don't have any experience with macOS as I am very new to this

**Comment by Derpitron** [comment]
This is weird. I'm not able to reproduce this issue locally, either by downloading the .ZIP file or by cloning the repository.

**Comment by Derpitron** [comment]
I think I know the cause of this issue.

On Mac OS and Linux, files starting with a period `.` are *hidden* by default. There should be an option in your file manager program to "see hidden files".

On Mac OS, press the `Command ⌘` + `Shift ⇧` + “.” (period) keys at the same time, which should show the hidden files looking transparent.

Let me know if this works for you, I do not have a Mac system to test this on.

**Comment by nightninja56** [comment]
That worked to show the .env file! Will update if everything works otherwise. Thanks so much!

**Comment by nightninja56** [comment]
Looks like I got it to work! fingers crossed it gets the job done eventually.
