### ISSUE TITLE
My id was hacked recently

### ISSUE THREAD

**Issue by MRELEC1R0N** [Derpitron/Discord-OTP-Forcer#27]
Hey my id was hacked recently and i can acces to the mail to reset the pass of it 
can i use it to bypass the 2fa ?

**Comment by LuXeZs** [comment]
This is made to enter randomly generated 2fa codes and enter them, so with time it should bypass the 2fa

**Comment by GarettBill** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me message him on telegram his telegram username is https://t.me/Blackhathacker111
