### ISSUE TITLE
Cannot pass "reset password" stage

### ISSUE THREAD

**Issue by YoDiscAlt** [Derpitron/Discord-OTP-Forcer#28]
I can run the script until it asks if I want to reset the password or not and asks me to input 1 or 2. No matter what I input, it is unresponsive from this point.

**Comment by Derpitron** [comment]
@LuXeZs is the one who has implemented the Password reset feature. I suggest you ask him for support here.

Please give some more information on this bug. What exactly happens? Any errors in the console/terminal/command prompt? Any glitches on the browser?

**Comment by LuXeZs** [comment]
@YoDiscAlt are you still having this issue? I've done a clean install on my system and I can't repeat the issue you seem to be having.

**Comment by Derpitron** [comment]
Hello, please update us.

**Comment by MKBastler** [comment]
I have the similar issue, where it opens the chrome window and enters the new password, but fails to enter any codes. Doesn´t matter whether 6 or 8 digit codes are being used.

**Comment by MKBastler** [comment]
_Also as a sidenote, the api-URL in the blocked URLs list is outdated, they use v10 now. Isn´t relevant for this issue tho._

**Comment by Derpitron** [comment]
@MKBastler @YoDiscAlt Let us know if the program works.

**Comment by MKBastler** [comment]
Yes it does. I simply replaced the placeholder text with the actual text and it instantly worked. Let´s see how long it takes until I can finally use my account again :)
