### ISSUE TITLE
Error Main.py

### ISSUE THREAD

**Issue by MafinKingg444** [Derpitron/Discord-OTP-Forcer#29]
cant find .env

**Comment by Derpitron** [comment]
https://github.com/Derpitron/Discord-OTP-Forcer/issues/24#issuecomment-1509614704 check this out and see if it fixes your issue

**Comment by MafinKingg444** [comment]
![Screenshot_2023-04-20-11-31-41-122_com.github.android.png](https://user-images.githubusercontent.com/86649046/233324025-4f1b3e77-3fd8-470e-8eaa-879bb147d551.png)

Line 4
 It cant find "dotenv"
By load_dotenv.

I can see and i have put in the informations in ".env"

**Comment by Derpitron** [comment]
have you installed all the packages using `pip install -r requirements.txt`?

**Comment by MafinKingg444** [comment]
First it didn't work but now its installt
