### ISSUE TITLE
Syntax error when trying to run main.py

### ISSUE THREAD

**Issue by dannycookie** [Derpitron/Discord-OTP-Forcer#34]
![image](https://user-images.githubusercontent.com/131943918/234768052-535b1194-6aa7-4b5b-9e8b-312979b0ddd5.png)
I get this error in command prompt when trying to run the file.

**Comment by Derpitron** [comment]
What python version are you using?

**Comment by dannycookie** [comment]
Whatever version it was, it was outdated :)
Installing the latest version worked. Thanks
