### ISSUE TITLE
I don't understand the installation

### ISSUE THREAD

**Issue by EdGamr** [Derpitron/Discord-OTP-Forcer#36]
I recently got hacked on discord, and the hacker enabled 2fa, i've been desperately trying to get my account back, and I found this! But the issue is that idk how it works. Can someone help me?

**Comment by LuXeZs** [comment]
See https://github.com/Derpitron/Discord-OTP-Forcer/issues/9 for some help.

I'm going to be writing up a full tutorial when I have so free time.

**Comment by Derpitron** [comment]
Hey, sorry @LuXeZs but I helped him resolve his issue privately.
