### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by mtsHDD** [Derpitron/Discord-OTP-Forcer#38]
Hello, sorry for my bad english, but I need a Help

When I use python src/main.py, the program ask me some questions of "Are you trying a password reset?" I respond "yes" and then "1".
The chrome window open but, the codes don't "pop-up". Nothing happens
![image](https://user-images.githubusercontent.com/132296007/235505619-ef47c7fe-7270-453c-ac06-1d6e40cbfe07.png)

**Comment by LuXeZs** [comment]
Answered here #31

**Comment by mtsHDD** [comment]
> Let me know if this issue persists after following the solution given in #31.

Yes, it's working. Now I just waiting they brute force the account, thx!
(By the way, I only changed the Browser language, than it's worked)
