### ISSUE TITLE
For a friend

### ISSUE THREAD

**Issue by unknowndra9** [Derpitron/Discord-OTP-Forcer#39]
Hello. I'm new here.
Bit of context, me and my friend were trying to stream a movie together and we were having audio and visual issues. Long story short, my friend tried to uninstall and reinstall Discord on her phone to so our stream can work properly. She ended up getting locked out of her account because she was unaware she had the 2aF authentication code enabled. So, with every attemps failed to get her account back, I decided to use Discord-OTP-Forcer to brute my way in.
Here where I came across a problem; I managed to get it worked, but then I got stuck with the error message "invalid token" on the login page:
![image](https://github.com/Derpitron/Discord-OTP-Forcer/assets/133023528/07ecfb80-4a28-40f2-a762-64b3a7739751)
What did I do wrong?

**Comment by Derpitron** [comment]
cc: @LuXeZs

**Comment by LuXeZs** [comment]
You only need the part after `https://discord.com/reset#token=` as it only needs the token it's self.

**Comment by unknowndra9** [comment]
So, how exactly can I get the token itself?
I kinda tried everything to get it at this point

**Comment by LuXeZs** [comment]
it's at the end of the URL so just copy everything else after `https://discord.com/reset#token=` for example,
 
`https://discord.com/reset#token=eyJpZCI6Ms34MjI0NTYwNjA3MDY4MTcxLCJlbWFpbCI6ImZsb3BwZXJzdmlAaG90bWFpbC5jb20ifQ.Y`

You just need to copy the `eyJpZCI6Ms34MjI0NTYwNjA3MDY4MTcxLCJlbWFpbCI6ImZsb3BwZXJzdmlAaG90bWFpbC5jb20ifQ.Y` and put that into the .env so you'd end up with it looking like this,

`TOKEN = eyJpZCI6Ms34MjI0NTYwNjA3MDY4MTcxLCJlbWFpbCI6ImZsb3BwZXJzdmlAaG90bWFpbC5jb20ifQ.Y`

If this doesn't fix it just let me know.

**Comment by unknowndra9** [comment]
I see. Let me try

**Comment by LuXeZs** [comment]
Just checking did this fix your issue?

**Comment by LuXeZs** [comment]
Is it a different issue or still invalid token?

**Comment by unknowndra9** [comment]
Still invalid token

**Comment by unknowndra9** [comment]
Yesterday

**Comment by unknowndra9** [comment]
I see. I tried a few times. So far, less success

**Comment by LuXeZs** [comment]
Could you possibly show me the page again?

**Comment by unknowndra9** [comment]
Should I let the program running overnight till it cracked the code or is it a bit too risky (might have a chance to get the account terminated)?

**Comment by LuXeZs** [comment]
@unknowndra9 Just checking in to see if your issue has been resolved or if there is anything else I can do to help you?

**Comment by unknowndra9** [comment]
Thanks for checking in! My issue has been resolved, thank you. Its been like 5 days since I have been running the Forcer (on the back up codes first). Last night it crashed because it reached maximum recursion. I started it up again, this time on the 6 numbered code, to see if this works. I'm not giving up on my friend just yet :)
