### ISSUE TITLE
Not very clear running instructions

### ISSUE THREAD

**Issue by EDGEG5** [Derpitron/Discord-OTP-Forcer#40]
how exactly am i going to run a .bat file on linux?, i use an arch linux based distribution, instructions number 2 and 4 are not very clear.

these instructions say to do the following

2. Go to the location you installed the repository and run setup.bat.
4. Run start.bat, Follow the instructions in the command prompt.

I had no problems when executing instructions 1 and 3, unless something is missing or wrong if anyone can help I appreciate it, I really need to recover my account but the discord as you can see makes things difficult on purpose without any intention to solve the problem. In the end, this is the only option left.

**Comment by Derpitron** [comment]
You'll have to "install" this program the normal way:
1. Download/clone the repo
2. Open the .env file and manually add the values
3. In Python 3, run:
```pip install -r requirements.txt```
4. Once the requirements are installed, run:
```python src/main.py```


Note:
Some users have reported that the program does not work on Linux. See #1 and #24.

**Comment by EDGEG5** [comment]
so in that case i will follow your advice and try to see if it will work using windows, i really appreciate your patience in looking into the details of the problem.

**Comment by LuXeZs** [comment]
@EDGEG5 Just checking in to see if your issue has been resolved or if you might need further assistance?

**Comment by glofia** [comment]
im using a Mac, as I don't have any windows or other systems. Im having a lot of trouble finding the env file, I have the requirements.txt file installed but im stuck at that step :,0

**Comment by Derpitron** [comment]
Closing stale isses
