### ISSUE TITLE
Unable to work

### ISSUE THREAD

**Issue by alonechicken** [Derpitron/Discord-OTP-Forcer#41]
Hi i'm unable to make the program work after entering the env file, is there something I'm doing wrong? do I leave the command file running after setting up the env file? should I just wait until a chrome tab opens? its been 20 min

**Comment by alonechicken** [comment]
nvm i have figured it out. Thankyou for creating this!

**Comment by alonechicken** [comment]
How do we get to the reset token page?

**Comment by LuXeZs** [comment]
Once you've run the `setup.bat` and filled in the necessary credentials in the `.env` file you should close the command prompt and run `start.bat`, This will open the command prompt again and ask if you're going to be doing a password reset.

> How do we get to the reset token page?

If you're looking to get the token then it's in the link you receive after you request a password reset, we have a guide with screenshots [here](https://github.com/Derpitron/Discord-OTP-Forcer#how-to-get-your-token) in the Readme.

**Comment by LuXeZs** [comment]
@alonechicken Just checking in to see if your issue has been resolved or if you might need further assistance?

**Comment by Derpitron** [comment]
Closing stale isses
