### ISSUE TITLE
Token has expired

### ISSUE THREAD

**Issue by Sgnd1** [Derpitron/Discord-OTP-Forcer#42]
-been trying to use it but it keeps saying (Token has expired) even though I just got the token...
 is there a way to fix this or am I doing something wrong?

**Comment by LuXeZs** [comment]
I'd recommend getting a new reset token as I can't seem to replicate this issue unless I use an old link.

**Comment by LuXeZs** [comment]
@Sgnd1 Just wanted to follow up and see if everything is sorted out or if there's anything else I can assist you with.

**Comment by Beezlebub3rd** [comment]
I think the problem is the <>, if you just remove them from the URL in the program-controlled tab it works fine.

**Comment by Derpitron** [comment]
Closing stale isses
