### ISSUE TITLE
Having an obscene amount of trouble

### ISSUE THREAD

**Issue by Len1739** [Derpitron/Discord-OTP-Forcer#43]
So, every time I try to do the 4th step (Running start.bat), it says that it doesn't detect Python. I have no clue what I'm supposed to do, as I have never coded stuff before.

**Comment by Len1739** [comment]
When I try to click the setup, it says that it can't find the .env, even though it's there.

**Comment by Len1739** [comment]
So, update: I downloaded Python off the Windows Store, which solved the previous post's problem.

However, it now says, "ModuleNotFoundError: no noduoe named dotenv"

I may need some help, still...
Step 4 is quite a challenge for me.

**Comment by Len1739** [comment]
Okay, so it turns out, 1. I had to truly activate the Python from Windows Store by clicking on it in start, and it even asked me if I specifically wanted either six or eight digit passwords. Now it is working. Terribly sorry for any annoyances I might've caused.

Hope this thread helps any passersby that have similar troubles to me throughout this day. ^^'

Hope you all get your accounts back, if you're reading this, too.

**Comment by Derpitron** [comment]
Uh... problem solved?

**Comment by Len1739** [comment]
Would it be okay if you left this open so that I can confirm when I get the account back, for the sake of reassuring people?

**Comment by Derpitron** [comment]
GitHub issues are solely for existing problems. If you've figured out how to use the program, then there's no need for it to remain open.
