### ISSUE TITLE
After installing

### ISSUE THREAD

**Issue by QuindariousG** [Derpitron/Discord-OTP-Forcer#44]
I'm having trouble on what exactly to do after downloading the original .zip file. I open it up and click setup.bat which opens cmd and says this:
Installing requirements...
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
Requirements installed!
Setup the .env file.

Then Notepad opens up and says:
Cannot find the C:\Windows\System32\.env file.
Do you want to create a new file?

If I click back to command, a new line below writes:
Press any key to continue . . .

What do I do?

**Comment by Len1739** [comment]
Have you downloaded Python off of Windows Store? Because I had that same problem.

**Comment by QuindariousG** [comment]
Yes, I have installed Python 3.11 from the Windows Store and have kept it open in the background.

**Comment by QuindariousG** [comment]
Update: I have the program running and no longer have any issues besides waiting for the right code. Thank you to everyone who has worked on this program!
