### ISSUE TITLE
Script does not work on Python < 3.10

### ISSUE THREAD

**Issue by Danneke12** [Derpitron/Discord-OTP-Forcer#47]
OS Windows 10
Phyton: Python 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)] on win32
After setting everything up, i'm getting the following error:

`File "D:\KutDiscord\Discord-OTP-Forcer-main\Discord-OTP-Forcer-main\src\main.py", line 271
    match menu:
          ^
SyntaxError: invalid syntax
Press any key to continue . . .`

**Comment by LuXeZs** [comment]
You'll need to update to Python 3.10 or above as older version don't have some of the features used in this.

**Comment by Derpitron** [comment]
Closing stale issues
