### ISSUE TITLE
[Feature Request] Re-open Chrome window upon Login TOTP code failure

### ISSUE THREAD

**Issue by Beezlebub3rd** [Derpitron/Discord-OTP-Forcer#49]
Got my password reset using this, works fine with that. However, once I hit an invalid session ticket with the login function, it doesn't open another Chrome window after closing it unlike with the password reset.

**Comment by Derpitron** [comment]
This is an intentional feature for now. This is to reduce the chance of ratelimit IP bans caused by spamming the servers with requests.

**Comment by Derpitron** [comment]
Implemented in aef8d206cdb659a06476b58a4df82010e97b873c. Let me know if it doesn't work!
