### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by AkunoNutz** [Derpitron/Discord-OTP-Forcer#50]
I am having issues setting this up and working could anyone help me

**Comment by Derpitron** [comment]
https://dontasktoask.com/

**Comment by Derpitron** [comment]
Tell us **exactly** what issues you have when setting up. Did you follow the instructions properly?

**Comment by AkunoNutz** [comment]
i just have an issue so my account is locked whenever i try to login it
says i need to reset my password to do so, i go to my email and press the
reset password link, then eneter my new password and it ask for my two
factor, how do i set up the whole thing ? i dont know what to do to make
this work or set it up im a noob and i dont think i set it up right

**Comment by Derpitron** [comment]
Follow the instructions given in the readme, if it doesn't work, let me know exactly what went wrong.

**Comment by Derpitron** [comment]
Do you have any issues setting up?

**Comment by Derpitron** [comment]
Closing stale issues
