### ISSUE TITLE
[Feature Request] Fill in known parts of backup code as a template for generator

### ISSUE THREAD

**Issue by Len1739** [Derpitron/Discord-OTP-Forcer#52]
Made this its own issue for the sake of simplicity.

**Comment by Len1739** [comment]
I may have gotten another idea:

Reusing certain passwords, but rearranging the characters every time?

**Comment by Derpitron** [comment]
That would be out of the scope of this program for now.

Besides, password brute forcers take an *infinite* amount of time to possibly get a correct entry.

You are better off mailing Discord for a Password Reset, and running this program in Password Reset mode.

**Comment by Len1739** [comment]
I was referring to reusing previously-used OTPs, but rearranging the characters. My apologies for not making it apparent.
