### ISSUE TITLE
Error on windows 11

### ISSUE THREAD

**Issue by konn-neko** [Derpitron/Discord-OTP-Forcer#53]
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found
  (Session info: chrome=113.0.5672.127)
  
  im not sure why i get this, i only get it after completing the hcaptcha

**Comment by LuXeZs** [comment]
Should be fixed in aef8d20.

**Comment by Derpitron** [comment]
Please download the latest version of this program and try again.
