### ISSUE TITLE
small issue with setup

### ISSUE THREAD

**Issue by AkunoNutz** [Derpitron/Discord-OTP-Forcer#56]
### Description

Traceback (most recent call last):
  File "C:\Users\achug\Discord-OTP-Forcer\main.py", line 55, in <module>
    userFacing(loadcfg())
  File "C:\Users\achug\Discord-OTP-Forcer\main.py", line 38, in userFacing
    if cfg['programMode'] not in validProgramModes: raise ValueError("Invalid program mode inputted!")
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Invalid program mode inputted!
Press any key to continue . . .

not sure what to do to fix this issue

### Minimal Reproduction

while set up

### Error

Traceback (most recent call last):
  File "C:\Users\achug\Discord-OTP-Forcer\main.py", line 55, in <module>
    userFacing(loadcfg())
  File "C:\Users\achug\Discord-OTP-Forcer\main.py", line 38, in userFacing
    if cfg['programMode'] not in validProgramModes: raise ValueError("Invalid program mode inputted!")
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Invalid program mode inputted!
Press any key to continue . . .

// not sure what to put in the "" for the progam modes i have tried true n flase but still isnt workin

### Operating System Version

windows 11 64bit

### Python Version

most newwst 

### Program Version 

none

**Comment by LuXeZs** [comment]
Haven't had much time to look over the new code and how everything works but from what I can see is you'll need to enter either `login` or `reset` in the `programMode: ""` and for `codeMode: ""` it's one of these `normal, backup, both`.

If this is wrong then @Derpitron should be able to give some more information on this.

**Comment by AkunoNutz** [comment]
what do you mean like this?

![image](https://github.com/Derpitron/Discord-OTP-Forcer/assets/134764274/51f5d5bf-c7da-4a80-ab4b-a69ca3542f57)

**Comment by AkunoNutz** [comment]
i added reset for both, then changed reset to only on of em and left on blank, i am still getting this error 

Traceback (most recent call last):
  File "C:\Users\achug\Discord-OTP-Forcer\main.py", line 55, in <module>
    userFacing(loadcfg())
  File "C:\Users\achug\Discord-OTP-Forcer\main.py", line 38, in userFacing
    if cfg['programMode'] not in validProgramModes: raise ValueError("Invalid program mode inputted!")
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Invalid program mode inputted!
Press any key to continue . . .

**Comment by LuXeZs** [comment]
```python
# Program mode configuration
# Lets you skip the initial mode prompt stage by filling in your desired
# programMode and codeMode beforehand.
programMode: "reset"
codeMode: "both"
``` 
Try setting it like this in the cfg.yml.

**Comment by Derpitron** [comment]
@LuXeZs is it posssible for you to make a Github Wiki page about the settings and how to use them?

**Comment by LuXeZs** [comment]
Yeah I'll get on it right now.

**Comment by Derpitron** [comment]
> Haven't had much time to look over the new code and how everything works but from what I can see is you'll need to enter either `login` or `reset` in the `programMode: ""` and for `codeMode: ""` it's one of these `normal, backup, both`.
> 
> If this is wrong then @Derpitron should be able to give some more information on this.

Yes, this is correct.

@AkunoNutz I am sorry for not writing proper instructions so far!
