### ISSUE TITLE
[bug] Program hangs after webdriver_manager reaches 100% download completion

### ISSUE THREAD

**Issue by Derpitron** [Derpitron/Discord-OTP-Forcer#63]
### Discussed in https://github.com/Derpitron/Discord-OTP-Forcer/discussions/62

<div type='discussions-op-text'>

<sup>Originally posted by **Windfave** June  9, 2023</sup>
after setting up the config (email, password, program mode and code mode, token) and turning on start.bat, a chrome tab opens up with discord and logs in, of course the captcha comes in. I complete that and then I am at the enter code screen.
However, nothing seems to be happening neither in the cmd or the chrome tab.

Am I doing something wrong?</div>

**Comment by LuXeZs** [comment]
@Windfave just want to check but is the browser language set to English as currently the program can only detect that

**Comment by Derpitron** [comment]
Duplicate of #64 . Check out that issue for more progress on this bug

**Comment by Windfave** [comment]
Sorry I didn't respond, yes, that fixes that, so it was truly because of the language @LuXeZs
