### ISSUE TITLE
[bug] Program hangs after webdriver_manager reaches 100% download completion

### ISSUE THREAD

**Issue by BBQChickenWYNGZ** [Derpitron/Discord-OTP-Forcer#64]
### Description

I downloaded everything the wiki section told me to followed the instructions like it said but then when I opened start.bat it opens a command prompt says downloading then opens google chrome goes to discord then just nothing appears to happen I let it do that for the entire day yesterday and let it run the entire night but nothing changed.

### Minimal Reproduction

I downloaded the zip file of the program downloaded the version of python the setup section told me to already had google chrome so I didn't have to download that then ran the setup.bat it downloaded a few things it opened the cfg.yml file I entered the information pressed continue it closed and so I ran the start.bat file it said it was downloading then opened chrome and then just nothing happened. 

### Error

![Screenshot 2023-06-13 003428](https://github.com/Derpitron/Discord-OTP-Forcer/assets/74160521/ffbaf755-ce70-414a-b535-492f725211a5)
![Screenshot 2023-06-13 003624](https://github.com/Derpitron/Discord-OTP-Forcer/assets/74160521/0e0a489b-fef6-4049-9458-e14ff762f8c0)

### Operating System Version

Windows 11

### Python Version

3.10

### Program Version 

[bff8a8f](https://github.com/Derpitron/Discord-OTP-Forcer/commit/bff8a8fb15e2eda714bbc6ad0f060e863b9d817e)

### Discussed in https://github.com/Derpitron/Discord-OTP-Forcer/discussions/62

<div type='discussions-op-text'>

<sup>Originally posted by **Windfave** June  9, 2023</sup>
after setting up the config (email, password, program mode and code mode, token) and turning on start.bat, a chrome tab opens up with discord and logs in, of course the captcha comes in. I complete that and then I am at the enter code screen.
However, nothing seems to be happening neither in the cmd or the chrome tab.

Am I doing something wrong?</div>

**Comment by Derpitron** [comment]
Fill in the Program Version so I can see what version is affected.

**Comment by LuXeZs** [comment]
Check the wiki [here](https://github.com/Derpitron/Discord-OTP-Forcer/wiki/How-to-setup-and-use#filling-out-the-cfgyml) and input the mode you want to use.

**Comment by BBQChickenWYNGZ** [comment]
> Check the wiki [here](https://github.com/Derpitron/Discord-OTP-Forcer/wiki/How-to-setup-and-use#filling-out-the-cfgyml) and input the mode you want to use.

i did i put login and both

**Comment by Derpitron** [comment]
@Windfave @BBQChickenWYNGZ Try disabling your anti-virus and running the program? (https://github.com/SergeyPirogov/webdriver_manager/issues/523)

**Comment by Derpitron** [comment]
@BBQChickenWYNGZ Try downloading the latest program version and see if it works.

**Comment by BBQChickenWYNGZ** [comment]
I disabled the anti virus and downloaded the latest version but I get the same problem also when I was doing the setup I got this not sure if could be part of the problem though.
![Screenshot 2023-06-18 114616](https://github.com/Derpitron/Discord-OTP-Forcer/assets/74160521/4c21dff2-6110-4d09-8441-e4913febaf8e)

**Comment by Derpitron** [comment]
> I disabled the anti virus and downloaded the latest version but I get the same problem also when I was doing the setup I got this not sure if could be part of the problem though. ![Screenshot 2023-06-18 114616](https://user-images.githubusercontent.com/74160521/246687063-4c21dff2-6110-4d09-8441-e4913febaf8e.png)

This issue is a Python problem, i.e not related to our program at all. Try this: https://superuser.com/questions/1372793/the-script-is-installed-in-directory-which-is-not-path

**Comment by Derpitron** [comment]
This issue doesn't seem to be observed by me or any other users recently. Closing for now, feel free to re-open if it reoccurs.
