### ISSUE TITLE
[Bug]: Some Codes Get Rate Limited But The Script Doesn't Detect 

### ISSUE THREAD

**Issue by RandomPerson54163** [Derpitron/Discord-OTP-Forcer#65]
### Description

When generating 8 digit backup codes, some codes get rate limited but the script doesn't detect that and writes it in used codes anyway. 

### Minimal Reproduction

For example:

Let's say the script tried the code "12345678" after that it tried the code "23456789" and when it tries the third code "34567890" 
It gets rate limited but the scripts doesn't detect that and writes it in used codes anyway and continues, even though it does detect the rate limit on the fourth code and tries that code again It doesn't try the third code ever. I tested it myself on my alt account I used the correct backup code right after I used 2 wrong backup codes It got rate limited and didn't log me in. I hope I was able to explain my problem. 

### Error

![screenshot](https://github.com/Derpitron/Discord-OTP-Forcer/assets/65165396/b9d01dbc-7e47-4fda-9c2f-dfa19512d66e)

### Operating System Version

Windows 10

### Python Version

3.11.4

### Program Version 

Newest One

**Comment by Derpitron** [comment]
This is actually a feature! Let me explain:

When a code gets "ratelimited", Discord blocks that code temporarily, meaning that it doesn't actually get inputted/submitted to Discord for authentication. Rather, it just gets rejected on that attempt. Thus, This feature

**Comment by RandomPerson54163** [comment]
Hello, thanks for the reply but that's not what I ment. I know that feature and that feature works, but what I mean is when the script inputs 2 codes the 3rd code always gets rate limited and the script doesn't say it got rate limited, It just says it didn't work and after it says it didn't work it tries a different code(4th code) and then says 4th code got rate limited but it doesn't re attempt the 3rd code it only tries the 4th code again.

**Comment by RandomPerson54163** [comment]
![1](https://github.com/Derpitron/Discord-OTP-Forcer/assets/65165396/399ec7b1-c968-482b-ab20-7a26905a4834)
![2](https://github.com/Derpitron/Discord-OTP-Forcer/assets/65165396/ad8329c2-8c11-4cd0-a62c-5f8105542b0b)

**Comment by LuXeZs** [comment]
@RandomPerson54163 Could you download the most recent version and see if it fixes this issue?

**Comment by realCraymotherlol** [comment]
> @RandomPerson54163 Could you download the most recent version and see if it fixes this issue?

That seemed to have fixed the issue 
![afbeelding](https://github.com/Derpitron/Discord-OTP-Forcer/assets/42814427/44a41111-d33f-4f79-9343-e03bc1147f79)

**Comment by RandomPerson54163** [comment]
> @RandomPerson54163 Could you download the most recent version and see if it fixes this issue?

I tested it and yes it fixed the issue but now there is an another problem. After It detects that the code got rate limited and tries the code a second time, if it gets rate limited again it doesn't detect. Ill post a screenshot to show.

**Comment by LuXeZs** [comment]
Just updated it to make sure it checks if it's rate limited a second time in a row.

**Comment by RandomPerson54163** [comment]
Yes It works perfectly now and detects every rate limit. Thanks! I hope I will be able to recover my account with this lol
