### ISSUE TITLE
[Bug]: ""Invalid"" Program Mode??

### ISSUE THREAD

**Issue by automaton-dreams** [Derpitron/Discord-OTP-Forcer#80]
### Description

I logged out of my main disc a few months ago and like a fool i deleted authy, so now im using this to try and get back in.

I looked thru here to fix a majority of the problems. I get the setup done, i click the start thing, and...it keeps saying that Im Doin It Wrong technically.
Ive *been* trying to use the Reset function and i type it out exactly like in the how-to, capitalizing and everything, and it's still saying its not valid.

Is there anything I can do about this or is it out of my hands?

### Minimal Reproduction

I haven't a clue why it's doing this! I follow everything down to the wire just to get this freaking thing working and it's being bratty about it I Guess.
I download python and chrome. i fix the pip thing. i allow the doohickeys.
...I admit I'm not to familiar with coding so this may be a dunce move on my part but I simply cannot understand why it wont run.

### Error

![Untitled](https://github.com/Derpitron/Discord-OTP-Forcer/assets/146812775/cbbe1508-42a3-45bc-8fed-03b0a673d056)

 which is a load of hogwash because I put in "Reset" and that should be valid >:o(

![image](https://github.com/Derpitron/Discord-OTP-Forcer/assets/146812775/8b3b1b6c-9192-4ccf-9bff-bd86d269da9c)

### Operating System Version

Windows 10

### Python Version

3.12

### Program Version 

a64775f

**Comment by Derpitron** [comment]
Hey! Sorry for the issue. You have to actually write `reset` with all lower-case for it to work.

However, I will make a change that allows capitalisation to work as well.

**Comment by Derpitron** [comment]
Patched in dd1094872728b6015d6041aa86834e7625c5cf63
