### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Katerang31** [Derpitron/Discord-OTP-Forcer#83]
### Description

Key Error TOTP

### Minimal Reproduction

i launched start.bat
first installed serenium and webhelper
and they 
TOTP error

### Error

TOTP

### Operating System Version

Windows 10

### Python Version

latest

### Program Version 

latest

### Any other information or context?

![image](https://github.com/Derpitron/Discord-OTP-Forcer/assets/78563324/c1d2d5cf-3258-4b93-9f03-73cd06d1ff20)

**Comment by Derpitron** [comment]
Please tell me the program version and python version you are using.

**Comment by Derpitron** [comment]
This error does not occur for me. Closing.
