### ISSUE TITLE
[Bug]: Backup code doesnt work

### ISSUE THREAD

**Issue by MrDark-3896** [Derpitron/Discord-OTP-Forcer#89]
### Description

The program works fine with the normal code verification, but when trying to use the backup codes method, the program brokes itselfs after reaching the other method mode and crashes somewhat (because it doesnt crash, it just stops working flat)

### Minimal Reproduction

I didnt try anything out of normal, just running the program as it was made

### Error

The program doesnt crash, but gives a stacktraces before stops working.

### Operating System Version

Windows 10

### Python Version

3.12

### Program Version 

e62aae0

### Any other information or context?

![image](https://github.com/Derpitron/Discord-OTP-Forcer/assets/150585545/a2aa3f89-77db-4338-b38b-176f270d5d4c)

![image](https://github.com/Derpitron/Discord-OTP-Forcer/assets/150585545/d590d9c1-eacc-4202-b70e-537ce46994e7)

**Comment by MrDark-3896** [comment]
Nevermind, i edited one line in backend.py and the 8 code function started to work properly

**Comment by Derpitron** [comment]
What exactly did you edit?

**Comment by Derpitron** [comment]
I've personally found that minimising the webdriver chrome window causes this sort of crash

**Comment by MrDark-3896** [comment]
> What exactly did you edit?

I added the console image, i thought i uploaded the first time, but since i didnt, i added. Sorry for the trouble

**Comment by Derpitron** [comment]
No, you haven't uploaded the actual change you made in the code. Please submit it as a pull request.

**Comment by MrDark-3896** [comment]
> No, you haven't uploaded the actual change you made in the code. Please submit it as a pull request.

Oh, Okay. Just made it. Sorry for the trouble again tho. Hope this helps you somewhat

**Comment by pervadingHeretic** [comment]
Can corroborate that I have been having similar issues after having downloaded the most recent updates, after the program seemed to start giving out on me since the last download. However, unlike them, I could not code to save my life, even despite having read what is presented in the pull request ( #90 ).
My system is also in English, if that is any help.

**Comment by Derpitron** [comment]
@pervadingHeretic please send a screenshot of the errors you're getting.

**Comment by pervadingHeretic** [comment]
I hope this works, I blurred out the same general things as the first user but am willing to talk/cooperate as I am _no expert_.

![pleasetellmeifiamamoron1](https://github.com/Derpitron/Discord-OTP-Forcer/assets/150976456/309c221a-f84e-47e6-b20b-386a35516037)
![pleasetellmeifiamamoron2](https://github.com/Derpitron/Discord-OTP-Forcer/assets/150976456/f8bb2dc2-eee5-4945-a571-0ea8a39c6d0a)

**Comment by Derpitron** [comment]
@LuXeZs could you please check this out? I'm busy atm

**Comment by LuXeZs** [comment]
@MrDark-3896 @pervadingHeretic Could you please download the latest version and tell me if that has fixed the issue.

**Comment by MrDark-3896** [comment]
> @MrDark-3896 @pervadingHeretic Could you please download the latest version and tell me if that has fixed the issue.

I Tried it, and it didnt crash. So everything fine
