### ISSUE TITLE
Help Please

### ISSUE THREAD

**Issue by aapano** [Derpitron/Discord-OTP-Forcer#9]
I'd like to ask for some help because when looking at the instructions I'm not sure how to download/clone a respository this is my first experience with this kind of stuff so help would be nice

**Comment by Derpitron** [comment]
Hello, my apologies for not seeing this comment earlier.

https://www.youtube.com/watch?v=GHUKKFEIQX4 Watch this video for some help with downloading a Github repository.

**Comment by GarettBill** [comment]
> I'd like to ask for some help because when looking at the instructions I'm not sure how to download/clone a respository this is my first experience with this kind of stuff so help would be nice

Same thing happened to me but thanks to Blackhathacker111 who helped me message him on telegram his telegram username is https://t.me/Blackhathacker111

**Comment by Derpitron** [comment]
Deleted a spam/phishing comment.
