### ISSUE TITLE
[Bug]: ElementNotInteractableException raised and program crash, when code submission button randomly becomes uninteractible.

### ISSUE THREAD

**Issue by SMG54321** [Derpitron/Discord-OTP-Forcer#95]
### Description

Program crashes with `NoSuchElementException` after random uptime of running.
Occurs independently of program mode.
Cause:
Code submission button on code entry page may randomly have an uninteractible state (appears as 3 pulsing "loading" dots) (probably due to a pending network request in the page). When the program attempts to click the button after the specified sleep timeout elapses, it tries to interact with the uninteractible button, raising `ElementNotInteractableException`. This then causes the rest of the program to collapse and crash.

When crashing, the program raises a bunch of other exceptions and prints random hex-code stack traces to the terminal. 

### Minimal Reproduction
Conditions for crash are random. 
1. Run the program normally.
2. Either on a slow internet connection or after considerable time elapsed, wait for the code submission button to appear "loading".
3. Program crashes if the button does not re-fix itself before the internal program timeout elapses.

### Error

![image (2)](https://github.com/Derpitron/Discord-OTP-Forcer/assets/51088182/58eed445-1229-4ea3-ab20-7bd6a25a25c7)
![image_2023-11-24_104352679](https://github.com/Derpitron/Discord-OTP-Forcer/assets/51088182/f10368d1-98ed-4911-b22b-c5f9fab6f4f6)

### Operating System Version

Widows 10

### Python Version

3.11, 3.12

### Program Version 

d1a5b0359dcd793e3d17846c3fdfb63919b34f13

**Comment by LuXeZs** [comment]
I'm unable to recreate this issue so I will need more information.
What happens with the Chrome window during all of this?

**Comment by SMG54321** [comment]
> I'm unable to recreate this issue so I will need more information. What happens with the Chrome window during all of this?

everything that you would expect it to do. go to the right screen and start punching in codes at randomly spaced out pulses. then suddenly, it doesnt do that and breaks. if you want i can try to figure out how to record one of my screens. maybe me clicking off the screen(s) was enough of a problem?

**Comment by SMG54321** [comment]
> > I'm unable to recreate this issue so I will need more information. What happens with the Chrome window during all of this?
> 
> everything that you would expect it to do. go to the right screen and start punching in codes at randomly spaced out pulses. then suddenly, it doesnt do that and breaks. if you want i can try to figure out how to record one of my screens. maybe me clicking off the screen(s) was enough of a problem?

everything looks like its working fine on chrome's end i think.

**Comment by SMG54321** [comment]
is this something on my end?

**Comment by SMG54321** [comment]
i think its the correct code thats breaking it, can you try to extract it from the exceptions and give it to me? in like email or something?

**Comment by SMG54321** [comment]
GetHandleVerifier [0x009572A3+45731]
        (No symbol) [0x008E2D51]
        (No symbol) [0x007D880D]
        (No symbol) [0x0080B940]
        (No symbol) [0x0080BE0B]
        (No symbol) [0x0083D1F2]
        (No symbol) [0x00828024]
        (No symbol) [0x0083B7A2]
        (No symbol) [0x00827DD6]
        (No symbol) [0x008031F6]
        (No symbol) [0x0080439D]
        GetHandleVerifier [0x00C60716+3229462]
        GetHandleVerifier [0x00CA84C8+3523784]
        GetHandleVerifier [0x00CA214C+3498316]
        GetHandleVerifier [0x009E1680+611968]
        (No symbol) [0x008ECCCC]
        (No symbol) [0x008E8DF8]
        (No symbol) [0x008E8F1D]
        (No symbol) [0x008DB2C7]
        BaseThreadInitThunk [0x75F1FCC9+25]
        RtlGetAppContainerNamedObjectPath [0x770F7C6E+286]
        RtlGetAppContainerNamedObjectPath [0x770F7C3E+238]
        
        GetHandleVerifier [0x009572A3+45731]
        (No symbol) [0x008E2D51]
        (No symbol) [0x007D86D0]
        (No symbol) [0x00808118]
        (No symbol) [0x0080774F]
        (No symbol) [0x00827FDC]
        (No symbol) [0x00804A4E]
        (No symbol) [0x00828254]
        (No symbol) [0x0083B7A2]
        (No symbol) [0x00827DD6]
        (No symbol) [0x008031F6]
        (No symbol) [0x0080439D]
        GetHandleVerifier [0x00C60716+3229462]
        GetHandleVerifier [0x00CA84C8+3523784]
        GetHandleVerifier [0x00CA214C+3498316]
        GetHandleVerifier [0x009E1680+611968]
        (No symbol) [0x008ECCCC]
        (No symbol) [0x008E8DF8]
        (No symbol) [0x008E8F1D]
        (No symbol) [0x008DB2C7]
        BaseThreadInitThunk [0x75F1FCC9+25]
        RtlGetAppContainerNamedObjectPath [0x770F7C6E+286]
        RtlGetAppContainerNamedObjectPath [0x770F7C3E+238]

its gotta be be one of these two! can you tell me the codes these alligned up to?

**Comment by Derpitron** [comment]
Man why are you creating so many issues, especially with weird ambiguous titles?

You've already made one issue before. Re-open that one, and put your other screenshots in it. Spamming this repo with issues will only make it harder for us to track each one.

**Comment by SMG54321** [comment]
> Man why are you creating so many issues, especially with weird ambiguous titles?
> 
> You've already made one issue before. Re-open that one, and put your other screenshots in it. Spamming this repo with issues will only make it harder for us to track each one.

i can do that?

**Comment by SMG54321** [comment]
> > Man why are you creating so many issues, especially with weird ambiguous titles?
> > You've already made one issue before. Re-open that one, and put your other screenshots in it. Spamming this repo with issues will only make it harder for us to track each one.
> 
> i can do that?

if you want an idea on how dumb i am, here it is!

**Comment by Derpitron** [comment]
@SMG54321 this might be too much of a time waste to ask.

But I think the only way we could find the cause of this bug is to literally monitor the program the entire time.

You could:

1. Stare at your screen with the program and terminal open, and keep an eye on when and what conditions the program crashes (assuming it even does)
2. Record your screen right when you start the program, keeping the Selenium window and the Terminal window open at the same time. Then stopping the recording if/when the program crashes. Then sending the recording to us/me.

I think this is the only way any of us can find the cause.

**Comment by SMG54321** [comment]
by program/selenium window, you mean the chrome one right? i can do that! i have OBS!

**Comment by Derpitron** [comment]
I mean recording both the chrome window AND your command prompt at the same time. Do it if you're able to. Would be very helpful

**Comment by SMG54321** [comment]
https://www.mediafire.com/file/vulc3x0f4t9oyim/2023-11-25_08-54-54.mkv/file

this link will let you download the vid that i recorded

**Comment by SMG54321** [comment]
i did, posted it in the original bug report #92

**Comment by SMG54321** [comment]
https://www.mediafire.com/file/vulc3x0f4t9oyim/2023-11-25_08-54-54.mkv/file

this is the vid

**Comment by Derpitron** [comment]
Thanks for the video. Now I know what's going on!

It was not a problem with the CSS Class name.

This is the entire course of the glitch: 
1. The Discord website takes ~4 seconds to accept the code after the submit button is pressed, locking the submission button. 
2. But the program expected the submission button to be interactible after 4 seconds. I.e the program didn't wait for the page to finish loading.
3. The program has no idea what to do, because the submit button isn't interactible.
4. The program raises the error: `selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable`.
5. Since the program has an error, the rest of it falls down and crashes painfully.

I think the solution to this problem is to somehow make the program "wait indefinitely" for the button to become interactible, without raising an exception.

**Comment by SMG54321** [comment]
> @SMG54321 I've implemented a check to see if the confirm button is clickable so hopefully this'll fix this issue.

ok, either me replacing the files of the last version broke the fix, or something else is going on!

https://www.mediafire.com/file/sje0j29t3pig6m2/2023-11-26_10-53-21.mkv/file

i really dunno why.

**Comment by SMG54321** [comment]
THATS WAS THE PROBLEM!!!

**Comment by SMG54321** [comment]
https://www.mediafire.com/file/3mw8x6btshex5m0/2023-11-26_12-07-40.mkv/file

this is weird

**Comment by Derpitron** [comment]
@LuXeZs The fix you made should be applied in **both** normal and backup mode; You've mistakenly added it only for the `backup` mode lol

https://github.com/Derpitron/Discord-OTP-Forcer/blob/3f2ce8e94f1c789439e61d6848c3e809e323c683/src/backend.py#L106-L116C10


I think I know the issue more clearly now, I may have misdiagnosed it before.

 It's not *just* the **code submission button**, but *also* the **code entry field** that becomes uninteractible.

![image](https://github.com/Derpitron/Discord-OTP-Forcer/assets/46134462/a21d867b-6cb9-4905-92f2-01063aa659fd)

See how the entry field (blue) is greyed out? That means it's uninteractible. I.e you can't click on it or type anything, which is what the program tries to do.

Meanwhile, the code submit button (red) merely shows the loading icon, is also uninteractible. I can't click on it when it's in the loading state.

**Comment by LuXeZs** [comment]
Alright added checks to see if the submit button is active before submitting the code, as well I added a check to see if the text field is also interactable.

**Comment by SMG54321** [comment]
> Hey, please don't give vague descriptions like "this is weird" when you upload another screenshot/recording of the bug. Instead describe the issue in text (whatever you see/think is happening). Im not at my computer all day so am not able to check and watch the recordings all the time. Hope you can understand 🙂

FUCC, i keep doing that and wonder why i dont get any decent help. i am so sorry!

**Comment by Derpitron** [comment]
@SMG54321 program has been updated. Please redownload (with your cfg.yml as usual) and test away, no need to record this time.

**Comment by Derpitron** [comment]
![image](https://github.com/Derpitron/Discord-OTP-Forcer/assets/46134462/69929188-0135-4980-a9a0-a939c357e754)
Seems to not work for me.

**Comment by SMG54321** [comment]
Unsure if this is related to this or not but i will put it here:

it seems to be either some sort of time out exception or something else.

the program tries to find some object with the loacation of 0x000002BB4EAA7F.  the error being is that there is no element (or symbol) somewhere. the main spot or thing it tries to look for is  ```
 GetHandleVerifier [0x007572A3+45731]
        (No symbol) [0x006E2D51]
        (No symbol) [0x005D880D]
        (No symbol) [0x0060B940]
        (No symbol) [0x0060BE0B]
        (No symbol) [0x0063D1F2]
        (No symbol) [0x00628024]
        (No symbol) [0x0063B7A2]
        (No symbol) [0x00627DD6]
        (No symbol) [0x006031F6]
        (No symbol) [0x0060439D]
        GetHandleVerifier [0x00A60716+3229462]
        GetHandleVerifier [0x00AA84C8+3523784]
        GetHandleVerifier [0x00AA214C+3498316]
        GetHandleVerifier [0x007E1680+611968]
        (No symbol) [0x006ECCCC]
        (No symbol) [0x006E8DF8]
        (No symbol) [0x006E8F1D]
        (No symbol) [0x006DB2C7]
        BaseThreadInitThunk [0x75F1FCC9+25]
        RtlGetAppContainerNamedObjectPath [0x770F7C6E+286]
        RtlGetAppContainerNamedObjectPath [0x770F7C3E+238]
```
this particular set of digits, variables, what ever, have shown up in EVERY attempt i made over the versions. its starting to feel like the pepe silvia scene in always sunny in philadelphia. sorry for not telling you the main issue, as it didnt properly register till now, but what ever is missing here has to be what im looking for! also, some sort of time out exception happened on top of the fact that this is missing! what ever is here has to be it
![image_2023-11-28_173611494](https://github.com/Derpitron/Discord-OTP-Forcer/assets/51088182/0d3af111-0485-44e2-8897-bb8cd5e5f450)

![image_2023-11-28_172247004](https://github.com/Derpitron/Discord-OTP-Forcer/assets/51088182/2e9ea9d0-e326-475f-9791-8cfc697aaf4b)

![image_2023-11-28_173651791](https://github.com/Derpitron/Discord-OTP-Forcer/assets/51088182/856c9bf5-506c-4cd7-8293-f3b93814373c)

![image_2023-11-28_173926149](https://github.com/Derpitron/Discord-OTP-Forcer/assets/51088182/dfd0e79c-a5af-4d39-8168-bb9f5fd38bd1)

![image_2023-11-28_173957206](https://github.com/Derpitron/Discord-OTP-Forcer/assets/51088182/3c6563ca-c787-4304-825f-31fa98393824)

![image](https://github.com/Derpitron/Discord-OTP-Forcer/assets/51088182/b906f525-64e3-41d5-a09a-449aa9aa418b)

**Comment by SMG54321** [comment]
i recorded a video of the same error happening. same exceptions and such. you might to add whatever is missing here!

https://www.mediafire.com/file/pqh8b7be4y5xrvm/2023-11-29_17-55-34.mkv/file

**Comment by Derpitron** [comment]
![image](https://github.com/Derpitron/Discord-OTP-Forcer/assets/46134462/0e9b30ac-7e8b-4c8e-a523-122041e8e69d)
This is the code working as intended believe it or not.

https://github.com/Derpitron/Discord-OTP-Forcer/blob/63891d78ca530dcf6f328d22cf2616671699214b/src/backend.py#L198

https://github.com/Derpitron/Discord-OTP-Forcer/blob/63891d78ca530dcf6f328d22cf2616671699214b/src/backend.py#L243

The program waits 10 seconds for the button to load. Since it didn't, it crashed. That's just how it works.

**Comment by Derpitron** [comment]
Should be guarded against in 2beb3ba48a6e34d6406e77f66cf2d7b8ca9b7593. This commit should hopefully fix the whole issue.

**Comment by Derpitron** [comment]
![image](https://github.com/Derpitron/Discord-OTP-Forcer/assets/46134462/e628614c-de6a-4e25-98b4-2060e3157530)
Works for me! @SMG54321 try it out.

**Comment by Derpitron** [comment]
No crashing. Im considering this solved, and @SMG54321 I am deleting the videos you posted since they contain sensitive info.
